# Generated by Django 4.2.3 on 2023-08-05 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_rename_key_post_id_postlike_postcomment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="likes",
            new_name="like_count",
        ),
        migrations.AddField(
            model_name="post",
            name="user_likes",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
