# Generated by Django 4.2.3 on 2023-08-05 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0005_remove_post_like_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="user_comments",
            field=models.ManyToManyField(
                blank=True, related_name="user_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
