# Generated by Django 4.2.3 on 2023-08-05 23:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_post_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
    ]
