# Generated by Django 4.2.3 on 2023-08-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_remove_post_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date",
            new_name="created_date",
        ),
        migrations.AddField(
            model_name="post",
            name="last_updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
