# Generated by Django 4.2.3 on 2023-08-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_rename_date_post_created_date_post_last_updated_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="comment",
            field=models.TextField(default=""),
        ),
    ]
