# Generated by Django 4.2.3 on 2023-08-06 02:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_postcomment_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postlike",
            old_name="created",
            new_name="created_date",
        ),
        migrations.AddField(
            model_name="postcomment",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postcomment",
            name="last_updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
